use DBUBBUS;
delimiter /
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_MENSAJE`(
IN PIV_MSGID			CHAR(48),
IN PIV_TIPOMENSAJE		CHAR(2),
IN PIV_SECUENCIA		CHAR(2),
IN PIV_CODSERVICIO		CHAR(5),
IN PIV_FECHAHORA		TIMESTAMP,
IN PIV_PROTOCOLOENTRADA	CHAR(2),
IN PIV_NODOBUS			VARCHAR(15),
IN PIV_ISSERVER			VARCHAR(15),
IN PIV_PAYLOAD			BLOB,
IN PIV_CODPARTICION		CHAR(6),
IN PIV_DIA				TINYINT
)
BEGIN
INSERT INTO T_MENSAJE (
MENS_MSGID
, MENS_TIPOMENSAJE
, MENS_SECUENCIA
, MENS_CODSERVICIO
, MENS_FECHAHORA
, MENS_PROTOCOLOENTRADA
, MENS_NODOBUS
, MENS_ISERVER
, MENS_PAYLOAD
, MENS_CODPARTICION
, MENS_DIA
)
VALUES
( 
PIV_MSGID
, PIV_TIPOMENSAJE
, PIV_SECUENCIA
, PIV_CODSERVICIO
, PIV_FECHAHORA
, PIV_PROTOCOLOENTRADA
, PIV_NODOBUS
, PIV_ISSERVER
, PIV_PAYLOAD
, PIV_CODPARTICION
, PIV_DIA 
);
COMMIT;
END/

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INS_TRANSACCION`(
IN PIV_MSGID CHAR(48)
, IN PIV_FECHAHORAINICIAL TIMESTAMP
, IN PIV_FECHAHORAFINAL TIMESTAMP
, IN PIV_INDORIGEN VARCHAR(30)
, IN PIV_CODSERVICIO CHAR(5)
, IN PIV_PROTOCOLOENTRADA CHAR(2)
, IN PIV_NODOBUS VARCHAR(15)
, IN PIV_ISERVER VARCHAR(15)
, IN PIV_MSGIDORIGEN VARCHAR(50)
, IN PIV_CAMPOAUDIT01 VARCHAR(50)
, IN PIV_CAMPOAUDIT02 VARCHAR(50)
, IN PIV_CAMPOAUDIT03 VARCHAR(50)
, IN PIV_CAMPOAUDIT04 VARCHAR(50)
, IN PIV_CAMPOAUDIT05 VARCHAR(50)
, IN PIV_CAMPOAUDIT06 VARCHAR(50)
, IN PIV_CAMPOAUDIT07 VARCHAR(50)
, IN PIV_CAMPOAUDIT08 VARCHAR(50)
, IN PIV_CAMPOAUDIT09 VARCHAR(50)
, IN PIV_CAMPOAUDIT10 VARCHAR(50)
, IN PIV_TIEMPOPROCESO DECIMAL(10,0)
, IN PIV_TIEMPOPROVEEDOR DECIMAL(10,0)
, IN PIV_TIPORESPUESTA CHAR(1)
, IN PIV_CODRESPUESTA VARCHAR(10)
, IN PIV_CODPARTICION CHAR(6)
, IN PIV_DIA TINYINT
)
BEGIN
INSERT INTO T_TRANSACCION
(
TRAN_MSGID
,TRAN_FECHAHORAINICIAL
,TRAN_FECHAHORAFINAL
,TRAN_INDORIGEN
,TRAN_CODSERVICIO
,TRAN_PROTOCOLOENTRADA
,TRAN_NODOBUS
,TRAN_ISERVER
,TRAN_MSGIDORIGEN
,TRAN_CAMPOAUDIT01
,TRAN_CAMPOAUDIT02
,TRAN_CAMPOAUDIT03
,TRAN_CAMPOAUDIT04
,TRAN_CAMPOAUDIT05
,TRAN_CAMPOAUDIT06
,TRAN_CAMPOAUDIT07
,TRAN_CAMPOAUDIT08
,TRAN_CAMPOAUDIT09
,TRAN_CAMPOAUDIT10
,TRAN_TIEMPOPROCESO
,TRAN_TIEMPOPROVEEDOR
,TRAN_TIPORESPUESTA
,TRAN_CODRESPUESTA
,TRAN_FECHAHORABD
,TRAN_CODPARTICION
,TRAN_DIA
)
VALUES
(
PIV_MSGID
, PIV_FECHAHORAINICIAL
, PIV_FECHAHORAFINAL
, PIV_INDORIGEN
, PIV_CODSERVICIO
, PIV_PROTOCOLOENTRADA
, PIV_NODOBUS
, PIV_ISERVER
, PIV_MSGIDORIGEN
, PIV_CAMPOAUDIT01
, PIV_CAMPOAUDIT02
, PIV_CAMPOAUDIT03
, PIV_CAMPOAUDIT04
, PIV_CAMPOAUDIT05
, PIV_CAMPOAUDIT06
, PIV_CAMPOAUDIT07
, PIV_CAMPOAUDIT08
, PIV_CAMPOAUDIT09
, PIV_CAMPOAUDIT10
, PIV_TIEMPOPROCESO
, PIV_TIEMPOPROVEEDOR
, PIV_TIPORESPUESTA
, PIV_CODRESPUESTA
, PIV_CODPARTICION
, PIV_DIA
);
COMMIT;
END/

delimiter ;